name: CuteAuth
description: 一个简易高效且安全的 Minecraft Bukkit 1.16.x 登录插件.
author: WindLeaf_qwq
website: https://windleaf.ml/
version: ${project.version}
main: ml.windleaf.cuteauth.CuteAuth
api-version: 1.16

commands:
  register:
    description: 注册命令
    usage: /register <password> <confirm password>
    aliases: [reg]
  login:
    description: 登录命令
    usage: /login <password>
    aliases: [l]
  logout:
    description: 注销命令
    usage: /lougout [cancel]
    aliases: [lout]
  cuteauth:
    description: CuteAuth 插件本体命令
    usage: /cuteauth <help/reload/version>

permissions:
  cuteauth.reload:
    default: op